In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df=pd.read_csv("data2.csv")

In [4]:
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.0,74,78.0,1.0,1,Pune
1,female,69.0,90,88.0,NaN,2,na
2,female,90.0,95,93.0,74.0,2,Nashik
3,male,47.0,57,NaN,78.0,1,Na
4,male,NaN,78,75.0,81.0,3,Pune
5,female,71.0,Na,78.0,70.0,4,na
6,male,12.0,44,52.0,12.0,2,Nashik
7,male,NaN,65,67.0,49.0,1,Pune
8,male,5.0,77,89.0,55.0,0,NaN

In [5]:
df.isnull()

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False
4,False,True,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False
7,False,True,False,False,False,False,False
8,False,False,False,False,False,False,True

In [6]:
series = pd.isnull(df["math score"])
df[series]

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
4,male,NaN,78,75.0,81.0,3,Pune
7,male,NaN,65,67.0,49.0,1,Pune

In [7]:
df.notnull()

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,True,True,True,True,True,True,True
1,True,True,True,True,False,True,True
2,True,True,True,True,True,True,True
3,True,True,True,False,True,True,True
4,True,False,True,True,True,True,True
5,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True
7,True,False,True,True,True,True,True
8,True,True,True,True,True,True,False

In [8]:
series1 = pd.notnull(df["math score"])
df[series1]

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.0,74,78.0,1.0,1,Pune
1,female,69.0,90,88.0,NaN,2,na
2,female,90.0,95,93.0,74.0,2,Nashik
3,male,47.0,57,NaN,78.0,1,Na
5,female,71.0,Na,78.0,70.0,4,na
6,male,12.0,44,52.0,12.0,2,Nashik
8,male,5.0,77,89.0,55.0,0,NaN

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])
newdf=df
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,0,72.0,74,78.0,1.0,1,Pune
1,0,69.0,90,88.0,NaN,2,na
2,0,90.0,95,93.0,74.0,2,Nashik
3,1,47.0,57,NaN,78.0,1,Na
4,1,NaN,78,75.0,81.0,3,Pune
5,0,71.0,Na,78.0,70.0,4,na
6,1,12.0,44,52.0,12.0,2,Nashik
7,1,NaN,65,67.0,49.0,1,Pune
8,1,5.0,77,89.0,55.0,0,NaN

In [10]:
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,0,72.0,74,78.0,1.0,1,Pune
1,0,69.0,90,88.0,NaN,2,na
2,0,90.0,95,93.0,74.0,2,Nashik
3,1,47.0,57,NaN,78.0,1,Na
4,1,NaN,78,75.0,81.0,3,Pune
5,0,71.0,Na,78.0,70.0,4,na
6,1,12.0,44,52.0,12.0,2,Nashik
7,1,NaN,65,67.0,49.0,1,Pune
8,1,5.0,77,89.0,55.0,0,NaN

In [11]:
missing_values = ["Na", "na"," "]
df = pd.read_csv("data2.csv", na_values = missing_values)
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.0,74.0,78.0,1.0,1,Pune
1,female,69.0,90.0,88.0,NaN,2,NaN
2,female,90.0,95.0,93.0,74.0,2,Nashik
3,male,47.0,57.0,NaN,78.0,1,NaN
4,male,NaN,78.0,75.0,81.0,3,Pune
5,female,71.0,NaN,78.0,70.0,4,NaN
6,male,12.0,44.0,52.0,12.0,2,Nashik
7,male,NaN,65.0,67.0,49.0,1,Pune
8,male,5.0,77.0,89.0,55.0,0,NaN

In [12]:
ndf=df
ndf.fillna(0)
ndf

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.0,74.0,78.0,1.0,1,Pune
1,female,69.0,90.0,88.0,NaN,2,NaN
2,female,90.0,95.0,93.0,74.0,2,Nashik
3,male,47.0,57.0,NaN,78.0,1,NaN
4,male,NaN,78.0,75.0,81.0,3,Pune
5,female,71.0,NaN,78.0,70.0,4,NaN
6,male,12.0,44.0,52.0,12.0,2,Nashik
7,male,NaN,65.0,67.0,49.0,1,Pune
8,male,5.0,77.0,89.0,55.0,0,NaN

In [13]:
df['reading score'] = df['reading score'].fillna(df['reading score'].median())
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.0,74.0,78.0,1.0,1,Pune
1,female,69.0,90.0,88.0,NaN,2,NaN
2,female,90.0,95.0,93.0,74.0,2,Nashik
3,male,47.0,57.0,NaN,78.0,1,NaN
4,male,NaN,78.0,75.0,81.0,3,Pune
5,female,71.0,75.5,78.0,70.0,4,NaN
6,male,12.0,44.0,52.0,12.0,2,Nashik
7,male,NaN,65.0,67.0,49.0,1,Pune
8,male,5.0,77.0,89.0,55.0,0,NaN

In [14]:
df['math score'] = df['math score'].fillna(df['math score'].mean())
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.000000,74.0,78.0,1.0,1,Pune
1,female,69.000000,90.0,88.0,NaN,2,NaN
2,female,90.000000,95.0,93.0,74.0,2,Nashik
3,male,47.000000,57.0,NaN,78.0,1,NaN
4,male,52.285714,78.0,75.0,81.0,3,Pune
5,female,71.000000,75.5,78.0,70.0,4,NaN
6,male,12.000000,44.0,52.0,12.0,2,Nashik
7,male,52.285714,65.0,67.0,49.0,1,Pune
8,male,5.000000,77.0,89.0,55.0,0,NaN

In [15]:
df['writing score'] = df['writing score'].fillna(df['writing score'].std())
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.000000,74.0,78.000000,1.0,1,Pune
1,female,69.000000,90.0,88.000000,NaN,2,NaN
2,female,90.000000,95.0,93.000000,74.0,2,Nashik
3,male,47.000000,57.0,13.363062,78.0,1,NaN
4,male,52.285714,78.0,75.000000,81.0,3,Pune
5,female,71.000000,75.5,78.000000,70.0,4,NaN
6,male,12.000000,44.0,52.000000,12.0,2,Nashik
7,male,52.285714,65.0,67.000000,49.0,1,Pune
8,male,5.000000,77.0,89.000000,55.0,0,NaN

In [16]:
df['Placement Score'] = df['Placement Score'].fillna(df['Placement Score'].min())
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.000000,74.0,78.000000,1.0,1,Pune
1,female,69.000000,90.0,88.000000,1.0,2,NaN
2,female,90.000000,95.0,93.000000,74.0,2,Nashik
3,male,47.000000,57.0,13.363062,78.0,1,NaN
4,male,52.285714,78.0,75.000000,81.0,3,Pune
5,female,71.000000,75.5,78.000000,70.0,4,NaN
6,male,12.000000,44.0,52.000000,12.0,2,Nashik
7,male,52.285714,65.0,67.000000,49.0,1,Pune
8,male,5.000000,77.0,89.000000,55.0,0,NaN

In [17]:
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.000000,74.0,78.000000,1.0,1,Pune
1,female,69.000000,90.0,88.000000,1.0,2,NaN
2,female,90.000000,95.0,93.000000,74.0,2,Nashik
3,male,47.000000,57.0,13.363062,78.0,1,NaN
4,male,52.285714,78.0,75.000000,81.0,3,Pune
5,female,71.000000,75.5,78.000000,70.0,4,NaN
6,male,12.000000,44.0,52.000000,12.0,2,Nashik
7,male,52.285714,65.0,67.000000,49.0,1,Pune
8,male,5.000000,77.0,89.000000,55.0,0,NaN

In [18]:
ndf.replace(to_replace = np.nan, value = -99)

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.000000,74.0,78.000000,1.0,1,Pune
1,female,69.000000,90.0,88.000000,1.0,2,-99
2,female,90.000000,95.0,93.000000,74.0,2,Nashik
3,male,47.000000,57.0,13.363062,78.0,1,-99
4,male,52.285714,78.0,75.000000,81.0,3,Pune
5,female,71.000000,75.5,78.000000,70.0,4,-99
6,male,12.000000,44.0,52.000000,12.0,2,Nashik
7,male,52.285714,65.0,67.000000,49.0,1,Pune
8,male,5.000000,77.0,89.000000,55.0,0,-99

In [19]:
ndf.dropna()

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.000000,74.0,78.0,1.0,1,Pune
2,female,90.000000,95.0,93.0,74.0,2,Nashik
4,male,52.285714,78.0,75.0,81.0,3,Pune
6,male,12.000000,44.0,52.0,12.0,2,Nashik
7,male,52.285714,65.0,67.0,49.0,1,Pune

In [20]:
ndf.dropna(how = 'all')

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.000000,74.0,78.000000,1.0,1,Pune
1,female,69.000000,90.0,88.000000,1.0,2,NaN
2,female,90.000000,95.0,93.000000,74.0,2,Nashik
3,male,47.000000,57.0,13.363062,78.0,1,NaN
4,male,52.285714,78.0,75.000000,81.0,3,Pune
5,female,71.000000,75.5,78.000000,70.0,4,NaN
6,male,12.000000,44.0,52.000000,12.0,2,Nashik
7,male,52.285714,65.0,67.000000,49.0,1,Pune
8,male,5.000000,77.0,89.000000,55.0,0,NaN

In [21]:
ndf.dropna(axis = 1)

,gender,math score,reading score,writing score,Placement Score,placement offer count
0,female,72.000000,74.0,78.000000,1.0,1
1,female,69.000000,90.0,88.000000,1.0,2
2,female,90.000000,95.0,93.000000,74.0,2
3,male,47.000000,57.0,13.363062,78.0,1
4,male,52.285714,78.0,75.000000,81.0,3
5,female,71.000000,75.5,78.000000,70.0,4
6,male,12.000000,44.0,52.000000,12.0,2
7,male,52.285714,65.0,67.000000,49.0,1
8,male,5.000000,77.0,89.000000,55.0,0

In [22]:
new_data = ndf.dropna(axis = 0, how ='any')
new_data

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.000000,74.0,78.0,1.0,1,Pune
2,female,90.000000,95.0,93.0,74.0,2,Nashik
4,male,52.285714,78.0,75.0,81.0,3,Pune
6,male,12.000000,44.0,52.0,12.0,2,Nashik
7,male,52.285714,65.0,67.0,49.0,1,Pune

In [26]:
df=pd.read_csv("data2.csv")
df

,gender,math score,reading score,writing score,Placement Score,placement offer count,Region
0,female,72.0,74,78.0,1.0,1,Pune
1,female,69.0,90,88.0,NaN,2,na
2,female,90.0,95,93.0,74.0,2,Nashik
3,male,47.0,57,NaN,78.0,1,Na
4,male,NaN,78,75.0,81.0,3,Pune
5,female,71.0,Na,78.0,70.0,4,na
6,male,12.0,44,52.0,12.0,2,Nashik
7,male,NaN,65,67.0,49.0,1,Pune
8,male,5.0,77,89.0,55.0,0,NaN

In [37]:
df['reading score'] = pd.to_numeric(df['reading score'], errors='coerce')
df['writing score'] = pd.to_numeric(df['writing score'], errors='coerce')
df['math score'] = pd.to_numeric(df['math score'], errors='coerce')

In [38]:
print(np.where(df['math score']>90))
print(np.where(df['reading score']<25))
print(np.where(df['writing score']<30))

(array([], dtype=int64),)
(array([], dtype=int64),)
(array([], dtype=int64),)

In [39]:
from scipy import stats

In [29]:
z = np.abs(stats.zscore(df['math score']))

In [30]:
print(z)

[nan nan nan nan nan nan nan nan nan]

In [31]:
threshold = 0.18

In [32]:
sample_outliers = np.where(z <threshold)
sample_outliers

(array([], dtype=int64),)

In [33]:
sorted_rscore= sorted(df['reading score'])
sorted_rscore

['44', '57', '65', '74', '77', '78', '90', '95', 'Na']

In [42]:
sorted_rscore = np.sort(df['reading score'].dropna())

q1 = np.percentile(sorted_rscore, 25)

print(q1)

63.0

In [ ]:
q3 = np.percentile(sorted_rscore, 75)
print(q1,q3)

62.0 74.0

In [ ]:
IQR = q3-q1

In [ ]:
lwr_bound = q1-(1.5*IQR)
upr_bound = q3+(1.5*IQR)
print(lwr_bound, upr_bound)

44.0 92.0

In [ ]:
r_outliers = []
for i in sorted_rscore:
  if (i<lwr_bound or i>upr_bound):
    r_outliers.append(i)
  print(r_outliers)

[1]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16]
[1, 16, 120]