In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
df = pd.read_csv("data3.csv")
df

     CustomerID   Genre  Age  Annual Income  Spending Score
0             1    Male   19          19000               0
1             2    Male   35          20000               0
2             3  Female   26          43000               0
3             4  Female   27          57000               0
4             5    Male   19          76000               0
..          ...     ...  ...            ...             ...
194         195    Male   28          89000               0
195         196    Male   34          43000               0
196         197  Female   30          79000               0
197         198  Female   20          36000               0
198         199    Male   26          80000               0

[199 rows x 5 columns]

In [50]:
df.info()
df

<class 'pandas.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      199 non-null    int64
 1   Genre           199 non-null    str
 2   Age             199 non-null    int64
 3   Annual Income   199 non-null    int64
 4   Spending Score  199 non-null    int64
dtypes: int64(4), str(1)
memory usage: 7.9 KB

     CustomerID   Genre  Age  Annual Income  Spending Score
0             1    Male   19          19000               0
1             2    Male   35          20000               0
2             3  Female   26          43000               0
3             4  Female   27          57000               0
4             5    Male   19          76000               0
..          ...     ...  ...            ...             ...
194         195    Male   28          89000               0
195         196    Male   34          43000               0
196         197  Female   30          79000               0
197         198  Female   20          36000               0
198         199    Male   26          80000               0

[199 rows x 5 columns]

In [6]:
df.describe()

       CustomerID         Age  Annual Income  Spending Score
count  199.000000  199.000000     199.000000      199.000000
mean   100.000000   30.306533   60633.165829        0.130653
std     57.590508    7.465849   30848.949453        0.337871
min      1.000000   18.000000   15000.000000        0.000000
25%     50.500000   26.000000   32500.000000        0.000000
50%    100.000000   29.000000   59000.000000        0.000000
75%    149.500000   35.000000   81500.000000        0.000000
max    199.000000   59.000000  150000.000000        1.000000

In [13]:
from sklearn import preprocessing
enc =  preprocessing.OneHotEncoder()
enc_df =  pd.DataFrame(enc.fit_transform(df[['Genre']]).toarray())
enc_df

       0    1
0    0.0  1.0
1    0.0  1.0
2    1.0  0.0
3    1.0  0.0
4    0.0  1.0
..   ...  ...
194  0.0  1.0
195  0.0  1.0
196  1.0  0.0
197  1.0  0.0
198  0.0  1.0

[199 rows x 2 columns]

In [24]:
df1 = df.join(enc_df)
df1

     CustomerID   Genre  Age  Annual Income  Spending Score    0    1
0             1    Male   19          19000               0  0.0  1.0
1             2    Male   35          20000               0  0.0  1.0
2             3  Female   26          43000               0  1.0  0.0
3             4  Female   27          57000               0  1.0  0.0
4             5    Male   19          76000               0  0.0  1.0
..          ...     ...  ...            ...             ...  ...  ...
194         195    Male   28          89000               0  0.0  1.0
195         196    Male   34          43000               0  0.0  1.0
196         197  Female   30          79000               0  1.0  0.0
197         198  Female   20          36000               0  1.0  0.0
198         199    Male   26          80000               0  0.0  1.0

[199 rows x 7 columns]

In [25]:
del df1['Genre']
df1

     CustomerID  Age  Annual Income  Spending Score    0    1
0             1   19          19000               0  0.0  1.0
1             2   35          20000               0  0.0  1.0
2             3   26          43000               0  1.0  0.0
3             4   27          57000               0  1.0  0.0
4             5   19          76000               0  0.0  1.0
..          ...  ...            ...             ...  ...  ...
194         195   28          89000               0  0.0  1.0
195         196   34          43000               0  0.0  1.0
196         197   30          79000               0  1.0  0.0
197         198   20          36000               0  1.0  0.0
198         199   26          80000               0  0.0  1.0

[199 rows x 6 columns]

In [54]:
df1.mean()

CustomerID          100.000000
Age                  30.306533
Annual Income     60633.165829
Spending Score        0.130653
0                     0.477387
1                     0.522613
dtype: float64

In [27]:
df1.mean(axis=0)

CustomerID          100.000000
Age                  30.306533
Annual Income     60633.165829
Spending Score        0.130653
0                     0.477387
1                     0.522613
dtype: float64

In [28]:
df1.mean(axis=1)

0       3170.166667
1       3339.666667
2       7171.666667
3       9505.333333
4      12670.833333
           ...
194    14870.666667
195     7205.166667
196    13204.666667
197     6036.500000
198    13371.000000
Length: 199, dtype: float64

In [32]:
df1.mean(axis=1)[0:4]

0    3170.166667
1    3339.666667
2    7171.666667
3    9505.333333
dtype: float64

In [33]:
df1.loc[:,'Age']

0      19
1      35
2      26
3      27
4      19
       ..
194    28
195    34
196    30
197    20
198    26
Name: Age, Length: 199, dtype: int64

In [38]:
df1.median()

CustomerID          100.0
Age                  29.0
Annual Income     59000.0
Spending Score        0.0
0                     0.0
1                     1.0
dtype: float64

In [37]:
df1.mode()

     CustomerID   Age  Annual Income  Spending Score    0    1
0             1  35.0        80000.0             0.0  0.0  1.0
1             2   NaN            NaN             NaN  NaN  NaN
2             3   NaN            NaN             NaN  NaN  NaN
3             4   NaN            NaN             NaN  NaN  NaN
4             5   NaN            NaN             NaN  NaN  NaN
..          ...   ...            ...             ...  ...  ...
194         195   NaN            NaN             NaN  NaN  NaN
195         196   NaN            NaN             NaN  NaN  NaN
196         197   NaN            NaN             NaN  NaN  NaN
197         198   NaN            NaN             NaN  NaN  NaN
198         199   NaN            NaN             NaN  NaN  NaN

[199 rows x 6 columns]

In [40]:
df1.min()

CustomerID            1.0
Age                  18.0
Annual Income     15000.0
Spending Score        0.0
0                     0.0
1                     0.0
dtype: float64

In [41]:
df1.max()

CustomerID           199.0
Age                   59.0
Annual Income     150000.0
Spending Score         1.0
0                      1.0
1                      1.0
dtype: float64

In [47]:
df.groupby(['Genre'])['Age'].mean()

Genre
Female    29.884211
Male      30.692308
Name: Age, dtype: float64

In [49]:
df.groupby(['Genre'])['Annual Income'].max()

Genre
Female    150000
Male      148000
Name: Annual Income, dtype: int64